#' @title Set Active Gene Panels for iSensor Analysis
#' 
#' @description 
#' Selects a predefined set of gene panels to use for subsequent analysis steps
#' in the iSensor pipeline. The specified panel set must exist in the iSensor object.
#'
#' @param iSensor_obj An iSensor analysis object created by \code{create_iSensor}
#' @param panelSet Name of the panel set to activate (default: 'allSpec_allHorm_allType')
#'
#' @return The modified iSensor object with updated active gene panels
#'
#' @examples
#' \dontrun{
#' # After creating an iSensor object:
#' iSensor_obj <- set_iSensor_workPanel(iSensor_obj, panelSet = "my_panels")
#' }
#'
#' @export
set_iSensor_workPanel <- function(iSensor_obj, panelSet = 'allSpec_allHorm_allType') {
    if (!(panelSet %in% names(iSensor_obj$genePanelSets))) {
        stop("Error: no such panel in iSensor_obj$genePanelSets")
    }

    getPanel <- iSensor_obj$genePanelSets[[panelSet]]
    iSensor_obj$genePanels <- getPanel

    return(iSensor_obj)
}

#' @title Add Expression Data to iSensor Object
#'
#' @description 
#' Updates or replaces the expression data matrix in an existing iSensor analysis object.
#' The input matrix should have genes as rows and samples as columns.
#'
#' @param iSensor_obj An iSensor object created by \code{create_iSensor}
#' @param data Numeric matrix of expression values (genes x samples)
#'
#' @return The modified iSensor object with updated expression data
#'
#' @examples
#' # Create initial object
#' iSensor_obj <- create_iSensor(data = matrix(rnorm(100), nrow = 10))
#' 
#' # Add new data
#' new_data <- matrix(rnorm(200), nrow = 10)
#' iSensor_obj <- add_iSensor_data(iSensor_obj, new_data)
#'
#' @export
add_iSensor_data <- function(iSensor_obj, data) {
    iSensor_obj$exprData <- data
    return(iSensor_obj)
}

#' @title Add Sample Labels to iSensor Object
#'
#' @description 
#' Adds or updates sample labels in an iSensor object. The labels must match
#' the number of samples (columns) in the expression data matrix.
#'
#' @param iSensor_obj An iSensor object created by \code{create_iSensor}
#' @param labels Character vector of sample labels (length must match number of samples)
#'
#' @return The modified iSensor object with updated sample labels
#'
#' @examples
#' # Create iSensor object
#' iSensor_obj <- create_iSensor(data = matrix(rnorm(100), nrow = 10))
#' 
#' # Add sample labels
#' sample_labels <- paste0("Sample", 1:10)
#' iSensor_obj <- add_iSensor_labels(iSensor_obj, sample_labels)
#'
#' @export
add_iSensor_labels <- function(iSensor_obj, labels) {
    if (length(colnames(iSensor_obj$exprData)) != length(labels)) {
        stop("Error: length of 'labels' does not match number of samples in iSensor expr data")
    }
    iSensor_obj$sampleLabels <- labels

    return(iSensor_obj)
}

#' @title Add Gene Panels to iSensor Object
#'
#' @description 
#' Adds new gene panels or updates existing panels in an iSensor object. 
#' Existing panels with matching names will be updated unless `drop = TRUE`.
#'
#' @param iSensor_obj An iSensor object created by `create_iSensor`
#' @param panels Named list of gene panels to add/update (each element should be a character vector of genes)
#' @param drop Logical indicating whether to replace existing panels (FALSE) or keep both (TRUE) (default: FALSE)
#'
#' @return The modified iSensor object with updated gene panels
#'
#' @examples
#' # Create iSensor object
#' iSensor_obj <- create_iSensor(data = matrix(rnorm(100), nrow = 10))
#' 
#' # Add new gene panel
#' new_panel <- list("MyPanel" = c("Gene1", "Gene2", "Gene3"))
#' iSensor_obj <- add_iSensor_workPanel(iSensor_obj, new_panel)
#'
#' @export
add_iSensor_workPanel <- function(iSensor_obj, panels, drop = FALSE) {
    havePanel <- names(panels) %in% names(iSensor_obj$genePanels)
    oldPanel <- panels[havePanel]
    newPanel <- panels[!havePanel]
    iSensor_obj$genePanels[names(oldPanel)] <- oldPanel
    iSensor_obj$genePanels <- c(iSensor_obj$genePanels, newPanel)
    return(iSensor_obj)
}

#' @title Add Panel Set to iSensor Object
#' 
#' @description 
#' Adds a new set of gene panels to an iSensor object. The panel set can be either
#' a single panel or multiple panels combined into a named set.
#'
#' @param iSensor_obj An iSensor object (created by `create_iSensor`)
#' @param panelsSet List of gene panels to add (either a single panel or multiple panels)
#' @param setName Optional name for the panel set (autogenerated if NULL)
#'
#' @return The modified iSensor object with the new panel set added to `genePanelSets`
#'
#' @examples
#' # Create iSensor object
#' iSensor_obj <- create_iSensor(data = matrix(rnorm(1000), nrow = 100))
#' 
#' # Add a new panel set
#' new_panels <- list(
#'   "CellCycle" = c("CDK1", "CDK2", "CCNB1"),
#'   "Apoptosis" = c("BAX", "BCL2", "CASP3")
#' )
#' iSensor_obj <- add_iSensor_panelSet(iSensor_obj, new_panels, setName = "MyPanels")
#'
#' @export
add_iSensor_panelSet <- function(iSensor_obj, panelsSet, setName = NULL) {
    if (is.null(setName)) {
        setName <- paste0('panelSet_', length(iSensor_obj$genePanelSets) + 1)
    }
    if(length(panelsSet) > 1) {
        # panelsSet <- setNames(panelsSet, setName)
        panelsSet_tmp <- panelsSet
        panelsSet <- list()
        panelsSet[[setName]] <- panelsSet_tmp
    }
    iSensor_obj$genePanelSets <- c(iSensor_obj$genePanelSets, panelsSet)

    return(iSensor_obj)
}







