#' @keywords internal
load_panel_from_rda <- function(file_path) {
  panelEnv <- new.env()
  load(file_path, envir = panelEnv)
  panelName <- ls(envir = panelEnv)
  if (length(panelName) != 1) {
    warning("Expected one object per panel file, got: ", paste(panelName, collapse = ", "))
  }
  panel <- get(panelName[[1]], envir = panelEnv)
  panel$name <- panelName
  check_iSensorsPanel_obj(panel)
  return(panel)
}

#' @keywords internal
load_panel_files <- function(panelsDir, files) {
  full_paths <- file.path(panelsDir, files)
  panel_objs <- lapply(full_paths, load_panel_from_rda)
  return(panel_objs)
}

#' @keywords internal
filter_and_load_panels <- function(panelsDir, species = NULL, hormone = NULL, type = NULL, filter = TRUE) {
  
  panelsFiles <- list.files(path = panelsDir, pattern = '\\.rda$', full.names = FALSE)
  
  if (filter) {
    name_delim <- '_'
    firstThreeParts <- lapply(strsplit(panelsFiles, name_delim), function(x) head(x, 3))
    all_species  <- unique(sapply(firstThreeParts, function(x) x[1]))
    all_hormones <- unique(sapply(firstThreeParts, function(x) x[2]))
    all_types    <- unique(sapply(firstThreeParts, function(x) x[3]))
    
    if (!is.null(species) && !any(species %in% all_species)) {
      stop('No such "species" found in files')
    }
    if (!is.null(hormone) && !any(hormone %in% all_hormones)) {
      stop('No such "hormone" found in files')
    }
    if (!is.null(type) && !any(type %in% all_types)) {
      stop('No such "type" found in files')
    }
    
    panelFilesToGet <- sapply(strsplit(panelsFiles, name_delim), function(x) {
      checkSpecies <- is.null(species) || any(species %in% x)
      checkHormone <- is.null(hormone) || any(hormone %in% x)
      checkType <- is.null(type) || any(type %in% x)
      all(c(checkSpecies, checkHormone, checkType))
    })
    panelsFiles <- panelsFiles[panelFilesToGet]
  }
  
  panel_objs <- load_panel_files(panelsDir = panelsDir, files = panelsFiles)
  panel_names <- sapply(panel_objs, function(p) p$name)
  panelsList <- setNames(lapply(panel_objs, function(p) p$genes), panel_names)
  return(panelsList)
}


#' Load and Prepare Gene Sensor Panels
#'
#' Loads gene sensor panels from default package data and optionally from custom directories,
#' allowing filtering by species, hormone, and panel type. Supports adding random gene panels
#' and meta panels with custom aggregation rules.
#'
#' @param setName Character. Name for the panel set to use.
#' @param species Character vector or NULL. Filter panels by species (e.g. "AT", "SL"). Default NULL (no filtering).
#' @param hormone Character vector or NULL. Filter panels by hormone (e.g. "aux", "cyt") category. Default NULL (no filtering).
#' @param type Character vector or NULL. Filter panels by type (e.g. "cis", "trans"). Default NULL (no filtering).
#' @param defaultPanels Logical. Whether to include default panels from package data. Default TRUE.
#' @param customPanels Logical. Whether to include custom panels from a local "iSensors/" folder. Default FALSE.
#' @param random Logical. Whether to add random gene panels automatically. Default TRUE.
#' @param randomInfo List or NULL. Custom settings for random gene panels; must contain fields 'n', 'sizes', 'majortrend'. Overrides `random` if provided.
#' @param metaPanels List or NULL. Meta panels with custom aggregation rules. Each element must be a list with 'srcPanels' (character vector) and 'rule' (function).
#'
#' @return An object of class \code{iSensorsPanelSet}, a list containing the loaded panels and additional metadata.
#'
#' @details
#' The function loads gene sensor panels stored as `.rda` files under the package's `extdata/geneSensors` folder,
#' filtering files by species, hormone, and type when specified. Custom panels can be loaded from a folder named `iSensors`
#' in the working directory.
#'
#' Random panels are generated by sampling gene names from the expression dataset, useful for statistical control.
#' Meta panels combine multiple existing panels with user-defined aggregation rules.
#'
#' @examples
#' \dontrun{
#' # Load default panels for Arabidopsis thaliana and auxin hormone
#' panelSet <- LoadSensors(
#'   setName = "ArabidopsisAuxin",
#'   species = "AT",
#'   hormone = "auxin",
#'   type = "cis",
#'   defaultPanels = TRUE,
#'   customPanels = FALSE,
#'   random = TRUE
#' )
#'
#' # Load panels including custom user panels and meta panels
#' metaPanels <- list(
#'   combined = list(
#'     srcPanels = c("panel1", "panel2"),
#'     rule = prod
#'   )
#' )
#'
#' panelSet2 <- LoadSensors(
#'   setName = "CustomSet",
#'   defaultPanels = TRUE,
#'   customPanels = TRUE,
#'   randomInfo = list(n = 3, sizes = c(100, 200, 300), majortrend = TRUE),
#'   metaPanels = metaPanels
#' )
#' }
#'
#' @export
LoadSensors <- function(setName, species = NULL, hormone = NULL, type = NULL,
                         defaultPanels = TRUE, customPanels = FALSE,
                         random = TRUE, randomInfo = NULL, metaPanels = NULL) {
  resultList <- list()
  if (defaultPanels) {
    defaultDir <- system.file("extdata/geneSensors", package = "iSensors")
    defaultPanelsList <- filter_and_load_panels(defaultDir, species, hormone, type)
    resultList <- c(resultList, defaultPanelsList)
  }
  if (customPanels) {
    customDir <- 'iSensors/'
    customDir_path <- file.path(getwd(), customDir)
    if (dir.exists(customDir_path)) {
      customPanelsList <- filter_and_load_panels(customDir_path, filter = FALSE)
      resultList <- c(resultList, customPanelsList)
    } else {
      message('No "iSensors" folder is found in the working directory, no custom panels will be used')
    }
  }
  
  # Создание additional
  additional <- list()
  
  if (isTRUE(random)) {
    # Пользователь запросил рандомы по умолчанию
    additional$random <- list(n = 2, sizes = c(200, 500), majortrend = TRUE)
  }
  
  if (!is.null(randomInfo)) {
    # Пользователь указал собственные настройки
    check_random_info(randomInfo)
    additional$random <- randomInfo
  }
  
  if (!is.null(metaPanels)) {
    check_metaPanels(metaPanels)
    additional$meta <- metaPanels
  }
  
  panelSet <- create_iSensorsPanelSet(name = setName, panelsList = resultList, additional = additional)
  return(panelSet)
}
